name: dart_blocks
description: An SDK written in Dart to communicate with Nuntio Blocks and Cloud
version: 0.1.77
homepage: https://github.com/nuntiodev

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  nuntio_blocks: ^0.0.11
  nuntio_cloud: ^0.0.1
  jwt_decoder: ^2.0.1
  protobuf: ^2.0.1
  grpc: ^3.0.2
  fixnum: ^1.0.0
  dart_jsonwebtoken: ^2.4.1
  flutter_secure_storage: ^5.0.2
  connectivity_plus: ^2.3.0
  uuid: ^3.0.6
  device_info_plus: ^3.2.3
  shared_preferences: ^2.0.13
  geolocator: ^8.2.0
  geocoding: ^2.0.4
dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.2
